version: '3.3'

# Servicios para la aplicacion
services:

  # Base de datos Postgres.
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=myStore
      - POSTGRES_USER=omju
      - POSTGRES_PASSWORD=omauri.Postgres0691
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  # Administrador pgAdmin para Postgres.
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=omju@mail.com
      - PGADMIN_DEFAULT_PASSWORD=omauri.Pgadmin0691
    ports:
      - 5050:80
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
