version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=myStore
      - POSTGRES_USER=omju
      - POSTGRES_PASSWORD=omauri.Postgres0691
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
